{{- define "myapp.fullname" -}}
{{- printf "%s-%s" .Release.Name .Chart.Name }}
{{- end }}

{{- define "myapp.deploymentName" -}}
{{- printf "%s-%s" .Release.Name "myapp-deployment" }}
{{- end }}

{{- define "myapp.serviceName" -}}
{{- printf "%s-%s" .Release.Name "myapp-service" }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "myapp.deploymentName" . }}
  labels:
    app: {{ template "myapp.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "myapp.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "myapp.fullname" . }}
    spec:
      containers:
        - name: myapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MESSAGE
              value: {{ .Values.message }}
