apiVersion: v1
kind: Service
metadata:
  name: fiber-application-{{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - name: rest
      port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: fiber
    component: application