apiVersion: v1
kind: Service
metadata:
  name: {{ template "myapp.serviceName" . }}
  labels:
    app: {{ template "myapp.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: {{ template "myapp.fullname" . }}
