apiVersion: v1
kind: Service
metadata:
  name: dp-maxwell-service
spec:
  selector:
    k8s-app: dp-maxwell
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
buntykumar@Buntys-MacBook-Pro templates % cat deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-maxwell
  labels:
    k8s-app: dp-maxwell
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: dp-maxwell
  template:
    metadata:
      labels:
        k8s-app: dp-maxwell
    spec:
      nodeSelector:
        processor: arm
      containers:
        - name: dp-maxwell
          image: {{ .Values.image }}
          ports:
            - name: dp-maxwell
              containerPort: 8080
              protocol: TCP
          env:
            - name: SERVICE_NAME
              value: dp-maxwell
            - name: DB_TYPE
              value: RDS
            - name: KAFKA_SECURITY_PROTOCOL
              value: SSL
            - name: ORG
              value: workden91
            - name: TENANT
              value: dp
            - name: KAFKA_ENDPOINT_WITH_PORT
              valueFrom:
                secretKeyRef:
                  name: fiber
                  key: KAFKA_ENDPOINT_WITH_PORT
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: fiber
                  key: MYSQL_HOST
            - name: MAXWELL_STORE_SCHEMA_PORT
              valueFrom:
                secretKeyRef:
                  name: fiber
                  key: MAXWELL_STORE_SCHEMA_PORT
            - name: MAXWELL_STORE_SCHEMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fiber
                  key: MAXWELL_STORE_SCHEMA_PASSWORD
            - name: MAXWELL_STORE_SCHEMA_USER
              valueFrom:
                secretKeyRef:
                  name: fiber
                  key: MAXWELL_STORE_SCHEMA_USER
            - name: MAXWELL_STORE_SCHEMA_HOST
              valueFrom:
                secretKeyRef:
                  name: fiber
                  key: MAXWELL_STORE_SCHEMA_HOST
            - name: MAXWELL_STORE_REP_PORT
              valueFrom:
                secretKeyRef:
                  name: fiber
                  key: MAXWELL_STORE_REP_PORT
            - name: MAXWELL_STORE_REP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fiber
                  key: MAXWELL_STORE_REP_PASSWORD
            - name: MAXWELL_STORE_REP_USER
              valueFrom:
                secretKeyRef:
                  name: fiber
                  key: MAXWELL_STORE_REP_USER
            - name: MAXWELL_STORE_REP_HOST
              valueFrom:
                secretKeyRef:
                  name: fiber
                  key: MAXWELL_STORE_REP_HOST
            - name: MAXWELL_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fiber
                  key: MAXWELL_STORE_PASSWORD
            - name: MAXWELL_STORE_USER
              valueFrom:
                secretKeyRef:
                  name: fiber
                  key: MAXWELL_STORE_USER
            - name: MAXWELL_STORE_HOST
              valueFrom:
                secretKeyRef:
                  name: fiber
                  key: MAXWELL_STORE_HOST
            - name: MAXWELL_STORE_DB
              valueFrom:
                secretKeyRef:
                  name: fiber
                  key: MAXWELL_STORE_DB
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 1m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: {{ .Values.imagePullPolicy }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      tolerations:
        - key: ""
          operator: "Exists"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 420
